/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedLibrariesIndexRouteImport } from './routes/_authenticated/libraries.index'
import { Route as AuthenticatedLibrariesIdRouteImport } from './routes/_authenticated/libraries.$id'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers.index'
import { Route as AuthenticatedServersIdRouteImport } from './routes/_authenticated/servers.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibrariesIndexRoute =
  AuthenticatedLibrariesIndexRouteImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrariesIdRoute =
  AuthenticatedLibrariesIdRouteImport.update({
    id: '/libraries/$id',
    path: '/libraries/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersIdRoute = AuthenticatedServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/$': typeof AuthenticatedSplatRoute
  '/system': typeof AuthenticatedSystemRoute
  '/libraries/$id': typeof AuthenticatedLibrariesIdRoute
  '/servers/$id': typeof AuthenticatedServersIdRoute
  '/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/$': typeof AuthenticatedSplatRoute
  '/system': typeof AuthenticatedSystemRoute
  '/': typeof AuthenticatedIndexRoute
  '/libraries/$id': typeof AuthenticatedLibrariesIdRoute
  '/servers/$id': typeof AuthenticatedServersIdRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/libraries/$id': typeof AuthenticatedLibrariesIdRoute
  '/_authenticated/servers/$id': typeof AuthenticatedServersIdRoute
  '/_authenticated/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/$'
    | '/system'
    | '/libraries/$id'
    | '/servers/$id'
    | '/libraries/'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/$'
    | '/system'
    | '/'
    | '/libraries/$id'
    | '/servers/$id'
    | '/libraries'
    | '/servers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/$'
    | '/_authenticated/system'
    | '/_authenticated/'
    | '/_authenticated/libraries/$id'
    | '/_authenticated/servers/$id'
    | '/_authenticated/libraries/'
    | '/_authenticated/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/': {
      id: '/_authenticated/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof AuthenticatedLibrariesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/$id': {
      id: '/_authenticated/libraries/$id'
      path: '/libraries/$id'
      fullPath: '/libraries/$id'
      preLoaderRoute: typeof AuthenticatedLibrariesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/$id': {
      id: '/_authenticated/servers/$id'
      path: '/servers/$id'
      fullPath: '/servers/$id'
      preLoaderRoute: typeof AuthenticatedServersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLibrariesIdRoute: typeof AuthenticatedLibrariesIdRoute
  AuthenticatedServersIdRoute: typeof AuthenticatedServersIdRoute
  AuthenticatedLibrariesIndexRoute: typeof AuthenticatedLibrariesIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLibrariesIdRoute: AuthenticatedLibrariesIdRoute,
  AuthenticatedServersIdRoute: AuthenticatedServersIdRoute,
  AuthenticatedLibrariesIndexRoute: AuthenticatedLibrariesIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
